sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .gradle
    - gradle
    - $HOME/.gradle
install:
  - true
script:
  - gradle build
notifications:
  on_failure: change # always|never
  on_success: change