language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .gradle
    - gradle
    - $HOME/.gradle
script:
  - ./gradlew clean build
notifications:
  on_failure: change # always|never
  on_success: change